kind: Template
apiVersion: v1
metadata:
  name: openshift-guru
  annotations:
    "openshift.io/display-name": DNS diagnostic tool
    description: |
      A simple utility pod with 'dig' and 'traceroute' for troubleshooting networking issues between pods
    iconClass: icon-cogs
    tags: "networking,dns,smoketest"
parameters:
- description: Pinger url
  name: TARGET_URL 
  value: http://hello
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: hello
    labels:
      name: hello
  spec:
    selector:
      name: hello
    ports:
    - name: http
      port: 80
      targetPort: http
- apiVersion: v1
  kind: Route
  metadata:
    name: hello
  spec:
    to:
      kind: Service
      name: hello
    port:
      targetPort: http
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for Hello app
    name: hello
  spec:
    replicas: 1
    selector:
      name: hello
    strategy:
      type: Rolling
      rollingParams:
         timeoutSeconds: 480
    template:
      metadata:
        labels:
          name: hello
        name: hello
      spec:
       containers:
        - image: docker.io/vnguyen/openshift-guru-hello:latest
          imagePullPolicy: Always
          name: hello
          ports:
          - 
            name: http
            containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for Pinger app
    name: pinger
  spec:
    replicas: 1
    selector:
      name: pinger
    strategy:
      type: Rolling
      rollingParams:
         timeoutSeconds: 480
    template:
      metadata:
        labels:
          name: pinger
        name: pinger
      spec:
       containers:
        - image: docker.io/vnguyen/openshift-guru-pinger:latest
          imagePullPolicy: Always
          name: pinger
          env:
          -
            name: TARGET
            value: ${TARGET_URL}

